#!/usr/bin/env ruby

#
#  ifbrother  --  Print to Brother MFC7420
#

require "rubygems"

require "pjl/appl"


class MFC7420Appl < PjlAppl

  include PJL

  RES = 600

  GS = %W(
    gs -q -dBATCH -dPARANOIDSAFER -dQUIET -dNOPAUSE
        -sDEVICE=ljet2p -r#{RES} -sOutputFile=- -
  )

  def frame
    job "#@login@#@host-#$$" do
      set :ras1200mode => :off
      set :resolution  => RES
      set :economode   => :off
      set :sourcetray  => :tray1
      set :mediatype   => :regular
      set :orientation => :portrait
      set :paper       => :a4
      set :pageprotect => :auto
      enter :pcl do
        pipe GS
      end
    end
  end

end

exit MFC7420Appl.run

